### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by stefaneicher** [posicks/mdnsjava#7]
Hi this example does not work
Lookup lookup = new Resolve("Test._org.smpte.st2071.service:service_v1.0._sub._mdc._tcp.local.");
ServiceInstance[] services = lookup.lookupServices();
for (ServiceInstance service : services)
{
    System.out.println(service);
}

I can not find the Resolve class.
I would recommend you to add these examples as test in your project.

Regards Stefan

**Comment by posicks** [comment]
Thank you Stefan.  I have corrected the issue.  The issue was introduced during an update to the API, resulting in a documentation error.

Thank you for the usage tests you have provided. I am in the process of implementing a Service variant of the API to consolidate the API into a single entry point for usage with OSGi and as a RESTful endpoint.  This breaks from the DNSJava paradigm, but ultimately I believe it will be easier to understand, use, and test, while exposing mDNS & DNS-SD capabilities to browser based applications.
